project:
  type: website
  output-dir: docs
    
execute:
  freeze: auto
  cache: true
  # eval: true
  echo: false
  # output: true
  # include: true
  warning: false
  error: false
  message: false

format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: images/logo-uantwerpen-sw-en-cmyk-pos.png
    footer: '[Online manuscript](https://jriveraespejo.github.io/paper2_manuscript/)'
resources:
  - 'UK group meeting.pdf'
